/*
 * This source file was generated by the Gradle 'init' task
 */
package POOexercise;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        Invoice invoice = new Invoice(1, "Item 1", -5, 20.0f);
        System.out.println("Valor total = " + invoice.getInvoiceAmount());
    }
}
