/*
 * This source file was generated by the Gradle 'init' task
 */
package RepetitionLoop;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        int number = 10;

        for (int i = 0; i <= number; i++) {
            System.out.println("Número: " + i);
        }
        System.out.println("Fim do loop!");
    }
}
