/*
 * This source file was generated by the Gradle 'init' task
 */
package MeuPrimeiroProjeto;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println("Olá Mundo!");
        System.out.println("Minha segunda linha de comando.");
    }
}
