/*
 * This source file was generated by the Gradle 'init' task
 */
package IMC;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        Person objectPerson = new Person();
        try (Scanner scanner = new Scanner(System.in)) {
            System.out.println("Enter the weight of the person: ");
            objectPerson.setWeight(scanner.nextFloat());

            System.out.println("Enter the height of the person: ");
            objectPerson.setHeight(scanner.nextFloat());

            System.out.println("IMC: " + objectPerson.calculateIMC());
        }
    }
}
