/*
 * This source file was generated by the Gradle 'init' task
 */
package Herança;

import java.util.Date;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Seller seller = new Seller();

        seller.setName("Paul");
        seller.setSalary(1000);
        seller.setCpf("123.456.789-00");
        seller.setBirthDate(new Date());
        seller.setCommissionPerItem(10.0);
        seller.setTotalItemsSold(10);

        System.out.println("Nome: " + seller.getName() + "\nSalário: " + seller.calculateSalary());
    }
}
